### ISSUE TITLE
RSS feed beinhaltet alle Seiten

### ISSUE THREAD

**Issue by samuelb** [reaktor23/website#15]
Ich hab gerade festgestellt, das der RSS feed https://reaktor23.org/index.xml alle Seiten von der Website beinhaltet und nicht nur den Blog.

**Comment by Bouni** [comment]
Will man denn evtl. nicht auch mibekommen wenn ein neues Projekt erstellt wird oder was an einem geändert wird?

**Comment by samuelb** [comment]
Ja, vielleicht. Aber man sollte dann eher unterschiedliche Feeds dafuer haben

**Comment by Bouni** [comment]
Evtl. auch einen News Feed, eine Projects feed und einen All Feed oder was in der Art!?

**Comment by samuelb** [comment]
https://gohugo.io/templates/rss/ beschreibt wie das funktioniert mit den RSS feeds.

https://reaktor23.org/blog/index.xml zeigt nur die blog posts, https://reaktor23.org/index.xml hingegen alles. Dem entsprechend zeigt https://reaktor23.org/projects/index.xml alle Projekte an.

Es ist alles prinzipiell alles erstmal da. Wir muessen nur ein weg finden das ordentlich zu verlinken.

**Comment by samuelb** [comment]
Ahaa, man bekommt immer den RSS Feed as Link im footer von der Seite die gerade anschaut.
