### ISSUE TITLE
Unklarer Zeitstempel im Reaktor Status

### ISSUE THREAD

**Issue by samuelb** [reaktor23/website#22]
Der Reaktor Status zeigt einen Zeitstempel an. Es steht aber nicht dabei, was dieser bedeuten soll.

Ausserdem ist die Darstellung sehr ausführlich: `Mon Oct 26 2020 14:14:50 GMT+0100 (Central European Standard Time)`. Vielleicht koennte man das noch kuerzen.

**Comment by samuelb** [comment]
Gefaellt mir schon besser. Aber der Zeitstempel ist in UTC, was aber nicht dran steht. Ich denke das kann fuer Verwirrung sorgen.

**Comment by Bouni** [comment]
🤔 Ok, dann schieb ich da nochmal was nach!

**Comment by Bouni** [comment]
@samuelb Ist der Zeitstempel wirklich in UTC?

Ich bekomm vom Powercommander den lastchange as float:

```
var lastchange_pwrcmder = 1603718090.851959
var fmtDate = new Date(lastchange_pwrcmder * 1000)
// Ergibt Date Mon Oct 26 2020 14:14:50 GMT+0100 (Central European Standard Time)

const dateformat = new Intl.DateTimeFormat('DE', { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit'});

var lastchange = dateformat.format(new Date(fmtDate))
// Ergibt 26.10.2020, 14:14
```

Der UTC Stempel wäre doch Ergibt 26.10.2020, **13**:14 oder?

**Comment by samuelb** [comment]
Ich hab vermutet er ist UTC. Es steht ja keine Zeitzone dran. Aber ja, wenn ich jetzt den JS code anschaue, ist das DE Zeit.

**Comment by Bouni** [comment]
Soll ich die Zeitzone noch dranschreiben!?

**Comment by samuelb** [comment]
Wenn du magst

**Comment by Bouni** [comment]
Eigentlich ist ja immer von der Zeitzone auszugehen in der der Reaktor liegt, oder?
Ich würde es so lassen
