### ISSUE TITLE
Update Bootstrap, JQuery etc

### ISSUE THREAD

**Issue by samuelb** [reaktor23/website#26]
Die Website verwendet unter anderen Bootstrap, JQuery und so weiter. Sie `themes/reaktor23/static/js/`. Die Libraries haben schon laenger kein Update mehr gesehen. Es waere schon wenn sich mal jemand erbarmen koennte, alle Libraries zu updaten und dabei flicken was auch immer kaputt geht.

**Comment by Bouni** [comment]
@samuelb Weisst du ob das ein custom build von bootstrap war damit die Texte usw. grün wreden?
Wenn ich das einfach mit dem default bootstrap.min.css überschreib wird alles blau!?

**Comment by Bouni** [comment]
![image](https://user-images.githubusercontent.com/948965/97453916-7cf08d00-1936-11eb-9996-ee7267b8462e.png)

![image](https://user-images.githubusercontent.com/948965/97453966-87128b80-1936-11eb-9c39-83f9053eb528.png)

**Comment by samuelb** [comment]
Ja, ich erinner mich dunkel. Ich glaub es gab nen Webservice bei dem man sich keine customized Bootstrap Version zusammen klicken konnte. Frag mich aber nicht was das war.
